### PR TITLE
Support AndroidX

### PR DESCRIPTION
**Pull request by ntvinhit**
Simply support AndroidX

### CODE REVIEW

**Comment by vmurin** [comment]
Please describe what is the need of this change. Actually even if the app uses androidx package the library can still use the old package. Or you encountered some issues?

**Comment by matiaskorhonen** [comment]
At least for me the android compile fails:

```
> Task :react-native-azure-auth:compileReleaseJavaWithJavac FAILED
/Users/matt/Code/MY-RN-APP/node_modules/react-native-azure-auth/android/src/main/java/com/auth/react/AzureAuthModule.java:9: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/matt/Code/MY-RN-APP/node_modules/react-native-azure-auth/android/src/main/java/com/auth/react/AzureAuthModule.java:10: error: cannot find symbol
import android.support.customtabs.CustomTabsIntent;
                                 ^
  symbol:   class CustomTabsIntent
  location: package android.support.customtabs
/Users/matt/Code/MY-RN-APP/node_modules/react-native-azure-auth/android/src/main/java/com/auth/react/AzureAuthModule.java:59: error: package CustomTabsIntent does not exist
            CustomTabsIntent.Builder builder = new CustomTabsIntent.Builder();
                            ^
/Users/matt/Code/MY-RN-APP/node_modules/react-native-azure-auth/android/src/main/java/com/auth/react/AzureAuthModule.java:59: error: package CustomTabsIntent does not exist
            CustomTabsIntent.Builder builder = new CustomTabsIntent.Builder();
                                                                   ^
/Users/matt/Code/MY-RN-APP/node_modules/react-native-azure-auth/android/src/main/java/com/auth/react/AzureAuthModule.java:60: error: cannot find symbol
            CustomTabsIntent customTabsIntent = builder.build();
            ^
  symbol:   class CustomTabsIntent
  location: class AzureAuthModule
5 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-azure-auth:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by vmurin** [comment]
Just compare your `build.gradle` files with ones from the [sample project](https://github.com/vmurin/react-native-azure-auth-sample) and add missing dependencies.
Also check `settings.gradle` file from the same project.

**Comment by vmurin** [comment]
Close due to missing committer activity

**Comment by c0d3blooded** [comment]
A note for anyone looking here. `jetifier` (forward) now accomplishes the same thing. For later RN versions

**Pull request closed without merging**
