### PR TITLE
Update AzureAuth.m

### PR DESCRIPTION
**Pull request by vuongductuanktmt**
Fix requiresMainQueueSetup.

### CODE REVIEW

**Comment by vmurin** [comment]
Hi,
Thank you for the update.
Can you please describe the need and effect of this change.

Kind regards
Vladi

**Comment by vuongductuanktmt** [comment]
> Hi,
> Thank you for the update.
> Can you please describe the need and effect of this change.
> 
> Kind regards
> Vladi

I received a warning
`YellowBox.js:67 Module AzureAuth requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
console.warn @ YellowBox.js:67
logToConsole @ RCTLog.js:47
logIfNoNativeHook @ RCTLog.js:30
__callFunction @ MessageQueue.js:366
(anonymous) @ MessageQueue.js:106
__guard @ MessageQueue.js:314
callFunctionReturnFlushedQueue @ MessageQueue.js:105
(anonymous) @ debuggerWorker.js:80`
Simulator Screen Shot - iPhone X - 2019-05-10 at 16 11 52

**Comment by vmurin** [comment]
So it is a good fix for the warning, but I'm not sure whether the boolean function should return "NO".
I would suppose to return "YES", as the AzureAuth native module uses UIWindow from UIKit and therefore should be initialized in main thread.

**Comment by vmurin** [comment]
Due to long silence in the conversation I close the issue with my own commit and reject this PR

**Pull request closed without merging**
